apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-ns
  namespace: codefresh
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/codefresh/roles/ingress-ns
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'