rbacEnable:
  enabled: true
ingress:
  domain: onprem-aks.codefresh.io
  rbacEnable: true

global:
  appProtocol: https
  appUrl: onprem-aks.codefresh.io

cfapi:
  gitlab:
    apiHost: gitlab-internal.codefresh.io
    loginHost: gitlab-internal.codefresh.io
    protocol: https