# Default values for helm-repo-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

# use SemVer image tag without PATCH numver
image:
  repository: r.cfcr.io/codefresh-inc/codefresh/helm-repo-manager
  tag: master
  pullPolicy: Always

service:
  name: helm-repo-manager
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

# set log level
logLevel: debug

# true - set log format to Codefresh JSON
logJSON: false

TestRepoUrlPrefix: "cm://local.codefresh.io/api/helm/repos"

postgres:
  port: 5432
  disableSSL: true

ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - helm-repo-manager.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
global:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nodeType
            operator: NotIn
            values:
            - internal
            - worker

# options for chartmuseum helm chart
chartmuseum:
  ingress:
    enabled: false
    # Used to create an Ingress record.
    hosts:
      - chartmuseum.local
    annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
  env:
    open:
      STORAGE: local
      DEPTH: 2
      DEBUG: "true"
      ALLOW_OVERWRITE: "true"
      DISABLE_API: "false"
      DISABLE_METRICS: "false"
      INDEX_LIMIT: 2500
