{{- $errors := "" }}
{{- if or (empty .Values.global.appUrl) (eq .Values.global.appUrl "your-domain.com") }}
{{-  $errors = printf "%s\n%s" $errors "global.appUrl is empty" }}
{{- end }}

{{- if empty .Values.firebaseSecret }}
{{-  $errors = printf "%s\n%s" $errors "firebaseSecret is empty" }}
{{- end }}

{{- if not ( empty $errors ) }} 
{{-  fail $errors }}
{{- end }}
