apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      {{- if .Values.redeploy }}
      annotations:
        forceRedeployUniqId: {{ now | quote }}
      {{- end }}
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
        version: {{ .Values.imageTag | quote }}
    spec:
      affinity:
{{ toYaml (default .Values.global.appServiceAffinity .Values.affinity) | indent 8 }}
      imagePullSecrets:
        - name: "{{ template "fullname" . }}-registry"
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
          {{- if .Values.global.env }}
          {{- range $key, $value := .Values.global.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end}}
          {{- end}}
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          - name: PORT
            {{- if .Values.global.maintenanceMode }}
            value: {{ .Values.global.maintenancePort | quote }}
            {{- else }}
            value: {{ .Values.port | quote }}
            {{- end }}
          - name: CODEFRESH_API_URL_PREFIEX
            value: "/api"
          - name: CODEFRESH_API_URL_BASE
            value: "{{ .Values.global.appProtocol }}://{{ .Values.global.appUrl }}"
          - name: ROLLBAR_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: rollbar-access-token
          - name: STRIPE_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: stripe-public-key
          # other licenses and keys
          - name: NEWRELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: newrelic-license-key
          - name: SEGMENT_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: segment-key
          - name: LOGGLY_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: loggly-token
          - name: SLACK_APP_ID
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: slack-app-id
          - name: SLACK_REDIRECTURI
            value: "{{ .Values.global.appProtocol }}://{{ .Values.global.appUrl }}/slack-return"
          - name: CF_REGISTRY_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: {{ template "fullname" . }}
                key: cfcr-domain
        ports:
        {{- if .Values.global.maintenanceMode }}
        - containerPort: {{ .Values.global.maintenancePort }}
        {{- else }}
        - containerPort: {{ .Values.port }}
        {{- end }}
          protocol: TCP
        {{- if .Values.global.addResolvConf }}
        volumeMounts:
        - mountPath: /etc/resolv.conf
          name: resolvconf
          subPath: resolv.conf
          readOnly: true
        {{- end }}
{{- if .Values.global.maintenanceMode }}
{{ toYaml .Values.global.maintenanceContainer | indent 6 }}
{{- end }}
      volumes:
      {{- if .Values.global.addResolvConf }}
      - name: resolvconf
        configMap:
          name: {{ .Release.Name }}-{{ .Values.global.codefresh }}-resolvconf
      {{- end }}
{{- if .Values.global.maintenanceMode }}
{{ toYaml .Values.global.maintenanceVolumes | indent 6 }}
{{- end }}
