apiVersion: batch/v1
kind: Job
metadata:
  name: codefresh-restore-job
spec:
 template:
  spec:
   initContainers:
   - name: aws-cli
     image: mesosphere/aws-cli
     env:
       - name: AWS_ACCESS_KEY_ID
         value: ...
       - name: AWS_SECRET_ACCESS_KEY
         value: ...
       - name: S3_URL
         value: s3://some-s3-bucket
       - name: BACKUP_TO_RESTORE
         value: cf-backup-20190217_103400.tar.gz
       - name: AWS_DEFAULT_REGION
         value: us-east-1
     command: 
       - "/bin/sh"
       - "-ec"
       - |
         cd /restored
         aws s3 cp $S3_URL/$BACKUP_TO_RESTORE $BACKUP_TO_RESTORE
         tar -xzvf $BACKUP_TO_RESTORE
     volumeMounts:
     - name: restored-data
       mountPath: /restored
   containers:
   - name: consul-restore
     image: consul
     command:
       - "/bin/sh"
       - "-ec"
       - |
         cd /restored/backup/*/consul
         echo "Starting Consul restore"
         curl -v -T consul.bkp http://cf-consul:8500/v1/snapshot
         echo "Consul restore completed successfully"
     volumeMounts:
     - name: restored-data
       mountPath: /restored
   - name: redis-restore
     image: codefresh/rdbtools:master
     env:
      - name: REDIS_PWD
        value: ...
     command:
       - "/bin/sh"
       - "-ec"
       - |
         cd /restored/backup/*/redis
         echo "Starting Redis restore"
         rdb --c protocol ./redis.bkp | redis-cli -u redis://cf-store:6379 -a $REDIS_PWD --pipe
         echo "Redis restore completed successfully"
     volumeMounts:
     - name: restored-data
       mountPath: /restored
   - name: mongo-restore
     image: mongo
     env:
       - name: MONGO_PWD
         value: ...
     command:
       - "/bin/sh"
       - "-ec"
       - |
         cd /restored/backup/*
         mongorestore mongo --host cf-mongodb:27017 -u root -p $MONGO_PWD --drop
         echo "Mongo restore completed successfully"
     volumeMounts:
     - name: restored-data
       mountPath: /restored
   restartPolicy: Never
   volumes:
   - name: restored-data
     emptyDir: {}