apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app: cf-local-volumes
    chart: local-volumes-1.0.0
    heritage: Tiller
    release: cf-local-volumes
  name: cf-builder-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/codefresh/cf-builder-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gke-alexaladov-onprem-te-default-pool-aae0907d-8lwz
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cf-local-storage

