apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: cf-local-volumes
    chart: local-volumes-1.0.0
    heritage: Tiller
    release: cf-local-volumes
  name: cf-builder-1
  namespace: codefresh
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: cf-local-storage
  volumeName: cf-builder-1

