---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tillerserviceaccount
  namespace: codefresh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tiller-binding
  namespace: codefresh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tiller-manager
subjects:
  - kind: ServiceAccount
    name: tillerserviceaccount
    namespace: codefresh
